---
title: "Name: Haofu Wang"
author: 
- |
    | Student number: 21112657
date: "`r format(Sys.time(), '%X, %d %B, %Y')`"
output: html_document
---

# Originality declaration

I, \[**insert your name**\], confirm that the work presented in this assessment is my own. Where information has been derived from other sources, I confirm that this has been indicated in the work.

date: `r format(Sys.time(), '%d %B, %Y')`

# Start your response here

# 1. Research Questions and Hypothesis

Q：Is there any relationship between a and b

H0 (Null Hypothesis): a and b has no relationship

H1 (Alternative Hypothesis): a and b has relationship

# 2. Initial project scope

Introduction part (Bullet Points)

-   Research Questions and Hypothesis

-   The reason why I choose this question

-   The main dataset for the analysis is ... (describe the data source)

-   Introduce the data scale. (It is a very large dataset, with around 66,000 rows, where each row represents an eviction with columns holding information such as the date executed, ejectment (possession or eviction), and spatial unit data such as community district and census tract.)

-   A brief intro of the data wangling and analysis. This may include research questions or hypotheses.

-   Identify the limitations and constrains of the dataset. It could be the spatial or temporal limitations.

-   Require 10-15 bullet points. Check the Week 10 lecture notes.

# 3. Set Up the Data

## 3.1 Read in Data

### 3.1.1 Load shapefile

### 3.1.2 Load csv

### 3.1.3 Transforming Data

projecting, making csv to a sf object etc.

## 3.2 Wrangling Data

### 3.2.1 Join data

### 3.2.2 select or filter columns

### 3.2.3 Data Cleaning

# 4. Analysis

## 4.1 Basic Analysis

### 4.1.1 柱状图

### 4.1.2 Map

## 4.2 Point Pattern Analysis (FOR SMALL AREA (HARROW))

### 4.2.1 Preparing Data for Analysis

### 4.2.2 Kernel Density Estimation

### 4.2.3 Ripley's K

## 4.3 DBSCAN (FOR SMALL AREA (HARROW))

## 4.4 Spatial Autocorrelation

### 4.4.1 Preparing Data for Analysis

## 4.5 Multiple Linear Regression

### 4.5.1 Preparing Data for Analysis

### 4.5.2 Basic Regression (散点图)

### 4.5.3 Assumption 1 - There is a linear relationship between the dependent and independent variables

1.  如果散点图画不出来，可以画频率分布图，如果频率分布图成正态分布，则说明两个变量存在一定程度的相关，很可能是线性相关。（7.5.6）（频率分布图可用两个变量分别对应任何变量画图（y = ..density..））
2.  使用symbox函数可得知对于坐标数据的最佳变换（log）
3.  

### 4.5.4 Assumption 2 - The residuals in your model should be normally distributed

### 4.5.5 Assumption 3 - No Multicolinearity in the independent variables

1.  将assump1中的呈正态分布的变量汇总在一起，查看与a1相比，R2是否有增长
2.  检查多重共线性先用相关系数矩阵
3.  VIF

### 4.5.6 Assumption 4 - Homoscedasticity

### 4.5.7 Assumption 5 - Independence of Errors

1.  Durbin-Watson test statistics
2.  残差值的空间自相关

### 4.5.8 Dealing with Spatially Autocorrelated Residuals - Spatial Lag and Spatial Error models （处理残差值的空间自相关，但是时间不允许）（7.6.11可用在limitation）（同样的还有GWR，可使分析更完整？）

# 5. Reflections (Conclusions) (1-3 Paragraphs)

-   The data I used -bias

-   The analysis I have applied (was it appropraite)

-   does it answer the research question/ hypothesis

-   if not, how not

-   what else could be considered

-   Assumptions that have been made

-   Definition of concepts

-   How could someone use this (be specific). How can this project help them.
